#pgadmin
#volume db

services:
  app:
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    environment:
      ENV: "production"
    ports:
      - "8000:8000"
    
  db:
    image: postgres
    container_name: fastapi-db
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data"
      ENV: "production"
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata/:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
