-- Active: 1724680656125@@127.0.0.1@5432@fastapi
CREATE SCHEMA fastapi;

CREATE TABLE "fastapi"."pings" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "url" VARCHAR(50) NOT NULL,
    "is_available" BOOLEAN NOT NULL,
    "ping" VARCHAR(50) NOT NULL,
    "time" VARCHAR(60) NOT NULL
)